project_id = "epjfoteyvejoqnigijrz"

[functions]
# Configure Edge Functions
[functions.stripe-webhook]
# Allow public access without authentication
verify_jwt = false
[functions.abacatepay-webhook]
# Allow public access without authentication
verify_jwt = false