project_id = "epjfoteyvejoqnigijrz"

[functions]
# Configure Edge Functions
[functions.stripe-webhook]
# Allow public access without authentication
verify_jwt = false
[functions.abacatepay-pix]
# Allow public access without authentication
verify_jwt = false
[functions.abacatepay-status]
# Allow public access without authentication
verify_jwt = false
[functions.abacatepay-webhook]
# Allow public access without authentication
verify_jwt = false
[functions.abacatepay-simulate]
# Allow public access without authentication
verify_jwt = false
[functions.debug-subscription]
# Allow public access without authentication
verify_jwt = false