project_id = "epjfoteyvejoqnigijrz"

[functions]
# Configure Edge Functions
[functions.debug-subscription]
# Allow public access without authentication
verify_jwt = false
[functions.send-verification-email]
# Allow public access without authentication
verify_jwt = false
[functions.password-reset]
# Allow public access without authentication
verify_jwt = false