// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../../types/supabase';

const SUPABASE_URL = "https://epjfoteyvejoqnigijrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwamZvdGV5dmVqb3FuaWdpanJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTk3OTUsImV4cCI6MjA2ODc3NTc5NX0.fSyTrP3EbKwQ-yXTdwOI7Nfj6ntNlF7otzbs3atQgM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
